apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    osd_pool_default_size = 3
    osd_pool_default_min_size = 2
    osd_pool_default_pg_num = 128
    osd_pool_default_pgp_num = 128
    [mon]
    mon_clock_drift_allowed = 0.50
    mon_clock_drift_warn_backoff = 10
    [osd]
    osd_journal_size = 10240

    

